#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "Honor 9 Lite"
#define BTM_BYPASS_EXTRA_ACL_SETUP TRUE

#define BLE_INCLUDED TRUE
#define BLE_VND_INCLUDED TRUE

#endif
